sles16.0: config.sh: remove logrotate config for cephadm
On the image, we have two logrotate configuration files. One for ceph
and one for cephadm. The one for ceph matches `/var/log/ceph/*.log` and
the one for cephadm matches `/var/log/ceph/cephadm.log`.

Having two logrotate configuration files for the same log file causes
logrotate to fail with the following error:

    error: /etc/logrotate.d/cephadm:2 duplicate log entry for
    /var/log/ceph/cephadm.log

To avoid this, we can simply remove the logrotate configuration file for
cephadm.

Signed-off-by: Tanguy Raufflet <tanguy.raufflet@savoirfairelinux.com>