.cqfd/sles15.7/Dockerfile: use kpartx instead of partx
Kiwi uses by default the partx utility to manipulate partitions in the
created .raw images. However, this doesn't work correctly in docker
containers. The image is mounted with losetup as /dev/loop* but the
partitions never appear as /dev/loop*p* after using "partx --add".
When building a .raw image, it gives the following error:

  KiwiMappedDeviceError: Device /dev/loop*p* does not exist

According to the maintainer of kiwi [1] this is due to the containerized
environment. Therefore, as proposed, configure kiwi to use kpartx
instead.

[1]: https://github.com/OSInside/kiwi/issues/2445#issuecomment-2334085301

Signed-off-by: Elinor Montmasson <elinor.montmasson@savoirfairelinux.com>